[package]
name = "audio"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/audio.rs"
doctest = false

[dependencies]
anyhow.workspace = true
collections.workspace = true
crossbeam.workspace = true
gpui.workspace = true
log.workspace = true
parking_lot.workspace = true
serde.workspace = true
settings.workspace = true
thiserror.workspace = true
util.workspace = true

[target.'cfg(target_env = "ohos")'.dependencies]
rodio = { git = "https://github.com/RustAudio/rodio", rev = "e50e726ddd0292f6ef9de0dda6b90af4ed1fb66a", default-features = false }

[target.'cfg(not(target_env = "ohos"))'.dependencies]
cpal.workspace = true
rodio.workspace = true
denoise = { path = "../denoise" }

[target.'cfg(not(any(target_env = "ohos", all(target_os = "windows", target_env = "gnu"), target_os = "freebsd")))'.dependencies]
libwebrtc.workspace = true
